### ISSUE TITLE
[Question] Will you be able to make a 3D robot/human-shaped assistant using this library?

### ISSUE THREAD

**Issue by ClarissaGazalaEvanthe** [nmfisher/thermion#16]
and can the entire body be moved using the dart script?

**Comment by nmfisher** [comment]
If you have a model already in glTF format, then yes.

You can play embedded glTF animations and you can also manually translate/rotate the mesh or bones, if that's what you mean by "moving".

**Comment by nmfisher** [comment]
I’ve actually done almost all the work for Linux support, it’s just missing a couple of platform method call handlers that were needed to migrate everything over to the new FFI framework. I’ll get around to it eventually, but it’s not a big priority for me at the moment.Feel free to close this issue if this answers your questions.Sent from my iPhoneOn 25 Nov 2023, at 3:12 PM, gwcangtip ***@***.***> wrote:﻿
Wow, I hope you can support the Linux platform for your library, thank you very much for making a great library
