### ISSUE TITLE
Some iOS devices with certain screen sizes crashes during createTexture

### ISSUE THREAD

**Issue by Hannnes1** [nmfisher/thermion#30]
I noticed an issue on the `develop` branch where some devices crashes with the error `Unable to bridge NSNumber to Int32`.

When investigating the issue I found that on some devices, the calculated widget dimensions aren't a whole number (i.e. they have a decimal that isn't zero), even if `.floor()` and `ceil()` are used. This can be seen in the following DartPad: https://dartpad.dev/?id=9590643146e16611ffd6a91c35b827be

Not sure why that is yet, but it can be fixed by moving the `.floor()` and `ceil()` to where `invokeMethod` is called.

I see that the code is a bit different on `feature/native-assets`, but I haven't been able to test that branch. Based on my test in DartPad (_rect2), it seems to be an issue there as well.

**Comment by nmfisher** [comment]
Thanks for the report. This should probably be fixed already on `feature/native-assets` branch as we're now passing viewport dimensions as integers, but I will leave this open until those are merged in so you can confirm it's OK on those devices too.

**Comment by Hannnes1** [comment]
Okay, great! Will report back once it is merged

**Comment by Hannnes1** [comment]
Can confirm that this is fixed now.
